urunc-dev/urunc

cmd/urunc/create.go
pkg/unikontainers/ipc.go
pkg/unikontainers/unikontainers.go

There are cases where the reexec process tries to connect to the init socket of urunc, before the socket gets created from the parent process. If the parent process does not manage to create and listen to the socket early enough, the reexec process will exceed its maximum tries to connect to init socket and it will fail. For that reason, we need to make sure that the init socket gets created before we spawn the reexec process.
This PR fixes  #5

Fix race condition of accessing the init socket on large number of containers

---

pkg/unikontainers/config.go
pkg/unikontainers/hypervisors/vmm.go
pkg/unikontainers/unikernels/unikernel.go
pkg/unikontainers/unikontainers.go

This PR adds support for unikernels requiring an initrd to run.
- Parse initrd annotation from OCI image: `com.urunc.unikernel.initrd`
- Add initrd field to ExecArg
- Add initrd info to Unikernel Params

Handle unikernels requiring initrd

---

pkg/unikontainers/hypervisors/qemu.go
pkg/unikontainers/unikernels/unikernel.go
pkg/unikontainers/unikernels/unikraft.go
pkg/unikontainers/unikontainers.go

Introduce support for booting up Unikraft unikernels over Qemu with urunc. The process of creating a bima container for Unikraft over Qemu is identical with Rumprun and hvt. However, in the case of Unikraft, we add support for initrd and we currently do not support any block storage over Qemu (e.g. virtio-blk), neither shared FS between guest and host. Therefore, if a user wants to pass any data inside the Unikraft unikernel, the user should create and add the initrd in the bima container.  Urunc is able to spawn Unikraft and Qemu guests without the need of devmapper.
Qemu support:
- virtio-net with a tap device
- initrd for guest's data
- static allocation of 256 MB for guest memory
Qemu TODOs:
- Add support for microvm
- Add support for virtio-blk
- Add support for virtio-fs
Unikraft …

Add support for booting Unikraft unikernels over Qemu

---

.gitignore
cmd/urunc/create.go
cmd/urunc/main.go
cmd/urunc/start.go
cmd/urunc/utils.go
docs/Performance-timestamping.md
go.mod
go.sum
pkg/metrics/metrics.go
pkg/unikontainers/unikontainers.go
script/performance/__modules__.py
script/performance/measure.py
script/performance/measure_single.py
script/performance/measure_to_json.py
tests/benchmarks/benchmark_test.go

This PR introduces timestamping logs to accurately measure `urunc`'s performance.
- Implement timestamp logging using zerolog to minimize overhead
- Develop Python scripts to gather timestamps
- Add documentation for enabling timestamping
- Add documentation for the Python scripts
Fixes: #9

Add timestamps to measure performance

---

tests/crictl/crictl_test.go
tests/ctr/ctr_test.go
tests/nerdctl/nerdctl_test.go

This commit adds end-to-end tests for booting Unikraft unikernels with Qemu using `nerdctl`, `ctr` and `crictl`.

Add end-to-end tests for Qemu-Unikraft

---

pkg/network/network.go
pkg/unikontainers/hypervisors/firecracker.go
pkg/unikontainers/hypervisors/vmm.go
pkg/unikontainers/unikontainers.go

Add initial support for booting unikernels over Firecracker with urunc. For the time being, we do not have support for virtio-blk, but only for initrd. THerefore, the guest can only read data from the initrd. Regarding networking, we use virtio-net  over the tap interface  that we create with urunc. Currently there is support for only one network device per guest. Moreover, in the case of Firecracker the guest's network interface has the same MAC address as the tap interface in the network namespace of the container.
Overall, things we need to consider in the future:
- Support for virtio-blk
- VM memory
- Generate Firecracker's configuration, based on a specific config
- Use Firecracker's API to spawn, instead of creating a JSON file
Fixes #8

Introduce support to boot up Firecracker with initrd

---

.github/resources/profiles.yml

For the VM test workflow, the default behavior should be to shutdown the VM after the test. If we debug stuff on a PR, we should be able to change this to false, so that the VM stays online and we can manually shut it down. Otherwise, it leaves stale VMs on our infra.
partially addresses https://github.com/nubificus/roadmap/issues/204

ci: Update shutdown flag

---

cmd/urunc/main.go
internal/constants/constants.go
pkg/unikontainers/unikontainers.go
tests/benchmarks/benchmark_test.go

Create internal pkg to hold constants. Setting all constants in a single place will help to manage constants in future versions.
Move timestamp logging output file declaration to new package.

internal: move constants to separate pkg

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/vm_test.yml

There are cases when the tests job fails. If we want to re-run the specific test job, it will probably be placed in the same github runner. The job id will remain the same, so it will try to overwrite the generated ssh key.
This is probably a bug on the ci logic, as we should cleanup the generated keys.

ci: Remove generated ssh key after artifact creation

---

cmd/urunc/create.go
cmd/urunc/utils.go
go.mod
go.sum
internal/constants/network_constants.go
internal/metrics/metrics.go
pkg/network/network.go
pkg/network/network_dynamic.go
pkg/network/network_static.go
pkg/unikontainers/unikontainers.go
tests/crictl/crictl_test.go

This PR brings support for dynamic and static network mode.
Static network mode allows urunc to be used to run Knative user functions packaged in unikernels.
In Knative, each user function container must run alongside a queue-proxy container inside the same pod.
To support this, we check if the current container is a queue-proxy container or a user-function container.
A ENV variable with a static IP is injected in the queue-proxy container before calling `runc` to actually execute it. 
Then, the user-function unikernel interface is assigned a static IP which is reachable by the queue-proxy container. 
In that way, the queue-proxy container can reach the user-function unikernel inside the same Pod / network namespace to provide the usual Knative functionality.
Dynamic network mode allows …

Network: Add static network mode

---

go.mod
go.sum
pkg/unikontainers/hypervisors/firecracker.go
pkg/unikontainers/hypervisors/hvt.go
pkg/unikontainers/hypervisors/qemu.go
pkg/unikontainers/hypervisors/vmm.go
pkg/unikontainers/unikontainers.go
tests/nerdctl/nerdctl_test.go

Introduce support to enable or disable seccomp filters for the VMM process that executes the unikernel. The seccomp filters will disallow access to system calls that are not required by the VMMs.  Seccomp support is targeting Hvt, Qemu and Firecrakcer. Moreover, the seccomp filters can be deactivated by using the `--security-opt seccomp=unconfined` command line option in nerdctl.
For the time being, we do not support custom seccomp filters, since we only want to reduce the system calls the VMM can do and not the ones of the application.

Introduce support for seccomp in VMMs

---

pkg/unikontainers/unikernels/unikernel.go
pkg/unikontainers/unikernels/unikraft.go

Unikraft was not following the unikontainer's unikernel interface. This commit aims to change that, by rewriting parts of the unikraft code to follow the interface that unikontainers defines for the various unikernels

Change Unikraft code to follow the unikernel interface

---

pkg/unikontainers/unikernels/rumprun.go
pkg/unikontainers/unikernels/unikernel.go
pkg/unikontainers/unikernels/unikraft.go
pkg/unikontainers/unikontainers.go

Change the way we initialize a unikernel struct reference and add three more functions in the unikernel interface.
Instead of creating a new unikernel struct directly, we split the creation and initialization of the unikernel struct. Therfore, at first, we simply create a new unikernel struct, based on the unikernel type and then we initialize it with the new Init function in the unikernel interface. The reason behind this change is to allow the use of unikernel-specific functions (e.g. SupportsBlock()) without initializing a new unikernel struct. In that way, we can use this function during the delete phase, as a check for devmapper cleaning.
Moreover, we add three more functions in the unikernel interface:
- Init(): which initializes the unikernel struct based on the unikernel arguments …

Enhance unikernel interface with functions to check supporting features

---

pkg/unikontainers/config.go
pkg/unikontainers/config_test.go
pkg/unikontainers/storage.go
pkg/unikontainers/storage_test.go
pkg/unikontainers/unikernels/unikernel.go
pkg/unikontainers/unikontainers.go
tests/nerdctl/nerdctl_test.go

Change the way we treat block devices and storage in urunc. In particular, we:
- Add annotation for specifying a block file inside a container. If this annotation is set then urunc will use this file as a block device if the respective unikernel framework supports block devices.
- Add annotation for specifying the mountpoint of a block device inside a unikernel.
- Add annotation and an environment variable for using the container's snapshot as a block device in the unikernel 
- Refactor the way we find and treat the container's devmapper snapshot, in order  to prepare it as a block for the unikernel.

Refactor the way we treat storage for unikernels

---

.github/workflows/unit_test.yml
Makefile

This PR adds a separate workflow to perform any unit tests, since there is no need to perform them inside the VM used for end-to-end tests.

ci: Add action for unit testing

---

.github/workflows/build.yml
.github/workflows/vm_test.yml
.gitignore
Makefile

Change the Makefile to enable the use of variables and flags for easier development. Moreover, enable the use of flags when invoking make, use the proper prerequisities for each target, remove the use of sudo inside the Makefile and add a help message. In addition, add more targets for building and testing:
- Dynamically-linked binaries
- Specific end-to-end tests
- Linting

Refactor and enhance Makefile targets

---

docs/Seccomp.md
pkg/unikontainers/hypervisors/hvt.go

Solo5-hvt requires a different set of system calls to execute from Go in Ubuntu 22.04. Therefore, we need to update the current list of allowed system calls in the seccomp filter of Solo5-hvt.
Given this opportunity, we introduce a new document to describe how urunc makes use of seccomp and how users can verify that seccomp does not create any issues for a platform that we have not tested. At last, the document also points to a toolset that can be used for identifying the required system calls.
Fixes https://github.com/nubificus/urunc/issues/49

Fix seccomp issue in Solo5-hvt for Ubuntu 22.04

---

cmd/urunc/create.go
cmd/urunc/delete.go
cmd/urunc/kill.go
cmd/urunc/run.go
cmd/urunc/start.go
cmd/urunc/utils.go
docs/Performance-timestamping.md
pkg/unikontainers/config.go
pkg/unikontainers/config_test.go
pkg/unikontainers/hypervisors/firecracker.go
pkg/unikontainers/storage.go
pkg/unikontainers/unikernels/rumprun.go
pkg/unikontainers/unikontainers.go
pkg/unikontainers/utils.go
pkg/unikontainers/utils_test.go

`urunc` needs to recognize normal containers from unikernel ones, since it can not handle them properly. For that reason, `urunc` check for specific annotations inside the container. If `urunc` specific annotations do not exist then `urunc` forwards the container handling in `runc`, otherwise, `urunc` handles the container.
However, the process of identifying the containers can be integrated with the process of getting information from the container (e.g. spec/state). Therefore, this PR merges these code paths, reducing the code, reading files etc.
Furthermore, this PR replaces hardcoded values in paths and annotations. Instead, constant values are introduced making easier to change values and reducing bugs.
The above changes fix issues such as the k3s issue …

Refactor handling of normal containers and replaces constants in paths and annotations

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/pr-approve.yml
.github/workflows/unit_test.yml
.github/workflows/vm_test.yml

As part of our CI update, we transition to github ARC runners. 
Base runner images are from https://github.com/some-natalie/kubernoodles, with some tweaks to account for the different flavors we require: https://github.com/nubificus/kubernoodles
This PR also updates the architecture abbrev (amd64 for x86_64 and arm64 for aarch64), so we should change the required tests in the repo settings.
Also addresses a bug in the PR-trailers workflow, where all labels 'ok-to-test' were removed when a PR was getting approved.

ci: Transition to ARC runners

---

pkg/unikontainers/hypervisors/firecracker.go
pkg/unikontainers/hypervisors/hvt.go
pkg/unikontainers/hypervisors/qemu.go
pkg/unikontainers/hypervisors/spt.go

We need to append a cmdline option for Unikraft to boot on FC.
Also reduce the default memory for all hypervisors.

Unikraft FC boot on arm64 and default memory

---

.github/workflows/vm_test.yml

When we spawn a VM to test urunc on a fresh installation we should not list the VMs already available on the host node.

ci: Remove debug step in E2E test

---

pkg/unikontainers/hypervisors/firecracker.go
pkg/unikontainers/hypervisors/hvt.go
pkg/unikontainers/hypervisors/qemu.go
pkg/unikontainers/hypervisors/spt.go
pkg/unikontainers/hypervisors/utils.go
pkg/unikontainers/hypervisors/vmm.go
pkg/unikontainers/unikontainers.go

This PR introduces the ability for users to specify the desired memory allocation for each workload. The specified memory is then passed as a parameter to the VMMs before launching a new Unikernel VM.

unikontainers: Add configurable memory

---

.github/workflows/ci.yml

Since we added `skip-build` / `skip-lint` labels, we want to trigger the CI jobs on label removal as well.

ci: Fix trigger when removing a label

---

README.md
docs/Installation.md
docs/Performance-timestamping.md
docs/Sample-images.md
docs/Urunc-Hypervisors.md
go.mod
go.sum
pkg/unikontainers/config.go
pkg/unikontainers/unikernels/rumprun.go
pkg/unikontainers/unikernels/unikernel.go
pkg/unikontainers/unikernels/unikraft.go
pkg/unikontainers/unikontainers.go
script/performance/__modules__.py
script/performance/measure_to_json.py
tests/crictl/crictl_test.go
tests/ctr/ctr_test.go
tests/nerdctl/nerdctl_test.go

This allows us to support multiple unikraft versions, since unikraft v0.16.1 introduced breaking changes.

unikernels: Add annotation and config field for unikernel version

---

.github/linters/typos.toml

Allow the user to be able to exclude either a line or a block of code from the spellcheck linter.

spellcheck: Let the user disable/enable spellcheck with comments

---

pkg/unikontainers/unikernels/unikraft.go

Unikraft, except of the network kernel arguments, changed the format for the kernel arguments regarding initrd. Therefore, similarly with the changes for the network arguments we change the arguments for initrd too.
In addition, we change the way we treat single word command line options, since we were not handling that case correctly.

Update unikraft kernel arguments for initrd and app's arguments

---

.github/resources/profiles.yml
.github/workflows/vm_test.yml
Makefile
tests/e2e/docker.go
tests/e2e/e2e_test.go

This PR introduces end-to-end tests to verify compatibility between `urunc` and `docker`. To achieve this, a new VM template is used where docker is properly installed and configured.

feat(testing): Add e2e tests for docker

---

Makefile
README.md

Add new Makefile rules to build urunc's docs locally and update the README with the respective information.

makefile(docs): Add Makefile rules for building the docs locally

---

tests/e2e/common.go

The tools that testing uses to spawn and manage containers, such as nerdctl docker and crictl, might print in stderr some warning messages. An example is the case of nerdctl and the use of systemd cgroups. In that scnearion, the testing code, which expects a specific output from the commands, will not work properly. For instance, when creating a new container and the warning is printed in stderr, the testing code treats this output as a container id.
TO resolve this issue, this commit removes the sue of CombinedOutput and separates stdout and stderr. If the execution of the command fails for any reason, then we combine the stdout with stderr and return the combined output.

fix(testing): Handle warnings during container operations

---

docs/Sample-images.md
docs/tutorials/How-to-urunc-on-k8s.md
pkg/unikontainers/hypervisors/hvt.go

The previous yaml was using an image that does not exist and it was also specifying the node to deploy the container. Hence, as pointed out in https://github.com/nubificus/urunc/issues/52#issuecomment-2561921038, the deployment was not successful.
This commit updates the image and removes the nodeName field. Moreover, a new nginx Rumprun image was created and addded in the list of existing images.

fix(docs): Update yaml in kubernetes tutorial

---

pkg/unikontainers/hypervisors/firecracker.go
pkg/unikontainers/hypervisors/hedge.go
pkg/unikontainers/hypervisors/hvt.go
pkg/unikontainers/hypervisors/qemu.go
pkg/unikontainers/hypervisors/spt.go
pkg/unikontainers/hypervisors/vmm.go
pkg/unikontainers/unikernels/rumprun.go
pkg/unikontainers/unikernels/unikernel.go
pkg/unikontainers/unikernels/unikraft.go
pkg/unikontainers/unikontainers.go
pkg/unikontainers/utils_test.go

As we want to add more and more unikernel frameworks and guests to urunc, there will be cases where a guest requires specific cli options to run on top of a monitor. The cli options might be related to network, block or other kinds of devices support. For that reason, we update the unikernel interface to include the following three more functions:
- MontirorBlockCli: For block specific cli options
- MontirorNetCli: For net specific cli options
- MontirorCli: For other monitor cli options
Also, we update the code before spawning the monitor, to allow the unikernels to define any specific cli options.

Update the unikernel interface and allow the use of unikernel-specific cli options when we spawn the Monitor

---

.github/resources/profiles.yml
.github/workflows/vm_test.yml

From January 30, Github stopped support for artifact@v3 and hence we need to update to v4.
For more information see: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Also, update the image we use for the end-to-end testing of `urunc` in order to use the latest Solo5.

Update test workflow and test VM image

---

.gitignore
pkg/unikontainers/hypervisors/firecracker.go
pkg/unikontainers/storage.go
pkg/unikontainers/unikontainers.go

Fix the handling of `devmapper` preparation as a block device for the VM. The main issue was the assumption that the rootfs directory of the container lies under the bundle directory.
Furthermore, use the container's rootfs as the CWD for the VMM execution.

Changes in the VMM's CWD and devmapper handling

---

.github/workflows/vm_test.yml

When spawning multiple concurrent runners that use the incus-remote-setup-action, the client name was shared across the runners. As a result, the first runner to reach the cleanup step would mark the client as unauthorized for all other runners. This commit fixes the issue by using a unique name for each client.

ci(deploy): Fix generic Incus client name conflict

---

docs/design/index.md
docs/package/index.md
docs/package/pre-built.md
docs/package/reuse.md
docs/package/rootfs.md
docs/unikernel-support.md
go.mod
go.sum

Update the x/net submodule of Go to cover CVE-2025-22872.
Furthermore, fix the dead links regarding the packaging page in the docs and update all bunnyfile snippets to use the latest version of bunny.

Update go x/net submodule and docs

---

.github/workflows/build-trigger.yml
deployment/urunc-deploy/Dockerfile

This PR fixes the build-trigger action to ensure that a new urunc-deploy Docker image is built even if the Dockerfile is not changed.

ci: fix build urunc-deploy action trigger

---

README.md
SECURITY.md
docs/developer-guide/security.md

Add a security policy for urunc to provide guidelines and an overview of the process for reporting security issues and vulnerabilities in urunc.

feat(docs): Add security policy for urunc

---

.github/workflows/build.yml
docs/developer-guide/security.md

Rename `aarch64` to `arm64` for consistency (and to re-enable the upload) of `arm64` binaries

Rename `aarch64` to `arm64` on binary upload jobs and correct docs broken link

---

.github/workflows/vm_test.yml

To enable the VM test action to work on forks/different orgs/renamed repos, we should clone the code using the `github.repository` variable, instead of the hardcoded entry.

ci: Fix hardcoded repo name for VM test

---

.github/linters/licenserc.yml
.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/ci_devel.yml
.github/workflows/ci_on_push.yml
.github/workflows/lint.yml
.github/workflows/unit_test.yml
.github/workflows/validate-files-and-commits.yml
.github/workflows/vm_test.yml

To be able to properly test both external (forked) and local branch-based PRs, we need to hack our way through Github Actions.
The issue is that since we moved to `pull_request_target` trigger (because we need secrets to upload binaries and trigger VM test jobs), the context of the github action that gets triggered is `main`. As a result, we need to explicitly check out the PRs' code to test it. This is fine with the actual (go) code, however, with the CI code this is different. There is no way we can test a change in a workflow using this method. 
To overcome this we follow the kata-containers approach, adding a manual trigger (`.github/workflows/ci_devel.yml`) that allows us to choose the branch (and thus the context) that the action will run. This adds the limitation that any change to …

ci: Cleanup & refactor CI to account for external PRs

---

.github/workflows/ci_on_push.yml

We re-enable the `ok-to-test` label. This label, if applied, allows the full CI workflow to run.
Also, when triggered from `pull_request_target`, make sure the `ref` points to the PR code, not `main`.

ci: Fix context and re-enable ok-to-test label

---

mkdocs.yml

We should probably automate this to point to the latest release? to the current state of the package? (current branch?) not sure.

docs: Fix link to urunc pkg

---

deployment/urunc-deploy/scripts/install.sh
docs/tutorials/How-to-urunc-on-k8s.md
docs/tutorials/Non-root-monitor-execution.md
pkg/unikontainers/hypervisors/firecracker.go
pkg/unikontainers/hypervisors/hedge.go
pkg/unikontainers/hypervisors/hvt.go
pkg/unikontainers/hypervisors/qemu.go
pkg/unikontainers/hypervisors/spt.go
pkg/unikontainers/hypervisors/vmm.go
pkg/unikontainers/rootfs.go
pkg/unikontainers/unikontainers.go

Add support to create a new rootfs which we will use to execute the monitor process. The new rootfs is based on the unikernel's container rootfs and we append all the necessary files and devices for the monitor execution. In particular, we perform the necessary steps to prepare the container's rootfs to become the new rootfs and append the below files and devs:
- The monitor binary
- `/dev/urandom`
- `/dev/null`
- `/dev/net/tun`: If the container has network
- `/dev/kvm`: If the monitor requires access to KVM.
- The snapshotter device if devmapper is used
In addition, since qemu is usually dynamically linked, we also need to append the shared objects from the libraries that it requires. This is not nice, but enough as a first step for a clean rootfs and helps us for a smoother transition …

Add support for the creation and change to a new rootfs for monitor execution

---

cmd/urunc/create.go
cmd/urunc/delete.go
cmd/urunc/kill.go
cmd/urunc/log_forward.go
cmd/urunc/main.go
cmd/urunc/run.go
cmd/urunc/start.go
cmd/urunc/utils.go
docs/developer-guide/development.md
pkg/network/network.go
pkg/network/network_static.go
pkg/unikontainers/config.go
pkg/unikontainers/hypervisors/firecracker.go
pkg/unikontainers/hypervisors/hvt.go
pkg/unikontainers/hypervisors/qemu.go
pkg/unikontainers/hypervisors/spt.go
pkg/unikontainers/ipc.go
pkg/unikontainers/storage.go
pkg/unikontainers/unikontainers.go

This pull request introduces a set of improvements aimed at enhancing logging clarity, consistency, and debugging capabilities:
- **Fix escaped `nsenter` logs**  
Replaces escaped characters in `nsenter` logs with properly formatted output via a custom formatter for improved readability.
- **Refactor sequential hook execution in unikontainers**  
Refactors hook execution to better handle errors, use `sync.WaitGroup` more cleanly, and allow detailed logging per hook.
- **Correct logging levels**  
Ensures consistent use of severity levels in log messages for clearer diagnostics.
- **Add optional syslog support**  
Introduces a new `--syslog` CLI flag that enables logging to syslog alongside other destinations for centralized logging and monitoring.
- **Uncapitalize error messages** …

fix: Improve logging and error handling

---

.github/workflows/vm_test.yml
Makefile

Remove dependency on self-hosted runners, since, for now, we don't test on ARM64.
Also, increase tests timeout to 8m since we parallelize them.

ci: Use GH runners for e2e VM testing

---

GOVERNANCE.md
docs/developer-guide/governance.md

Add draft project governance project, based on CNCF-council and a subset of Kata-container's concept.

docs: Add project governance

---

cmd/urunc/create.go
cmd/urunc/main.go
cmd/urunc/utils.go
docs/tutorials/How-to-urunc-on-k8s.md
go.mod
go.sum
pkg/network/network.go
pkg/network/network_dynamic.go
pkg/network/network_static.go
pkg/unikontainers/config.go
pkg/unikontainers/hypervisors/firecracker.go
pkg/unikontainers/hypervisors/hedge.go
pkg/unikontainers/hypervisors/hvt.go
pkg/unikontainers/hypervisors/qemu.go
pkg/unikontainers/hypervisors/spt.go
pkg/unikontainers/hypervisors/vmm.go
pkg/unikontainers/unikontainers.go
pkg/unikontainers/utils.go
tests/benchmarks/benchmark_test.go

Replace the references to the previous repository of urunc (github.com/nubificus/urunc) with the new and correct url github.com/urunc-dev/urunc.
This change might be necessary to trigger the replacement of the old repository with the new one in pkg.go.dev too.

chore: Replacce references of old repository in code and docs

---

.github/workflows/ci.yml
.github/workflows/ci_on_push.yml
.github/workflows/vm_test.yml

Add end to end tests for arm64 architecture.
Currently, only solo5-spt tests are supported for arm64 runners.

ci: Add arm64 tests

---

.github/contributors.yaml
.github/dependabot.yml
.github/linters/commitlint.config.js

Create a sample dependabot config for go and github-actions.

ci: Add dependabot

---

.github/linters/urunc-dict.txt
pkg/unikontainers/rootfs.go
pkg/unikontainers/storage.go
pkg/unikontainers/unikontainers.go
pkg/unikontainers/utils.go
pkg/unikontainers/utils_test.go

Since we are not able to handle the mount list when we have a block-based rootfs for the guest, at least copy all the files from the mount list of the container inside the rootfs of the guest. This is not very nice, yet it is the only possible way to pass some files defined in the mount list of the container inside the VM.
Furthermore, change copyFIle and make it more generic to allow defining the full path of the new file and not just its directory.

Copy the files defined in the mount list of the container inside the block rootfs of the VM

---

.github/contributors.yaml
cmd/urunc/create.go
cmd/urunc/delete.go
cmd/urunc/kill.go
cmd/urunc/main.go
cmd/urunc/run.go
cmd/urunc/start.go
cmd/urunc/utils.go
go.mod
go.sum

refactor(cli): Migrate from urfave/cli v1 to v3
This commit refactors the entire command-line interface layer to support
the breaking changes introduced in urfave/cli v3. The migration modernizes
the API usage and aligns the codebase with the new library conventions.
The key changes include:
- Updated the module import path to `github.com/urfave/cli/v3`.
- Replaced the top-level `cli.App` with a root `cli.Command` struct.
- Removed the deprecated `cli.Context` object from all handler functions.
- Updated all handler signatures to accept `context.Context` and
`*cli.Command` as arguments.
- Modified all flag and argument accessors to use methods on the
`*cli.Command` object instead of the old context.
Signed-off-by: Sankalp <sankalp@jarvis.local>

refactor(cli): Migrate from urfave/cli v1 to v3   #Issue Number 132

---

.github/workflows/vm_test.yml

In newer versions of gcc in aarch64 Solo5 fails to build successfully. A small patch is required and we have submitted a PR. However, until the issue gets resolved, use our fork with the patch included.
This is submitted as separate PR in order to revert it easily when the issue gets resolved.

fix(ci): Use our fork for building solo5

---

.github/linters/urunc-dict.txt
pkg/unikontainers/utils_test.go
tests/e2e/crictl.go

Fix some new issues reported from the go linter.
However, in the case of crictl.go file, the temporary solution of ignoring the error has been used. The linter complains about copying lock values that exist in both PodSandboxConfig/ContainerConfig structs. However, to properly fix this, we should either redefine them or implement a custom marshal function that ignores locks. Since, we only use this for creating a json file for crictl testing, ignoring this error is not that bad.

fix(linting): Fix some new linting errors
