urunc-dev/urunc

pkg/unikontainers/unikontainers.go
In our performance analysis, we identified a bottleneck linked to the sequential execution of hooks. Through the implementation of concurrent execution for these hooks, we've successfully achieved a remarkable reduction in their overall impact, bringing it down to nearly one-third of its previous level. This improvement is anticipated to enhance the overall performance of urunc, including the boot time of unikernel "containers".
=> Execute hooks concurrently to improve performance

.github/resources/cloudinit.yml, .github/resources/config.yml, .github/resources/profiles.yml, .github/workflows/vm_test.yml, tests/crictl/crictl_test.go, tests/ctr/ctr_test.go, tests/nerdctl/nerdctl_test.go, tests/utils.go
- Refactor tests for readability reusability
- Add end-to-end tests for Firecracker - Unikraft unikernels
- Add action to spawn VM and run end to end tests
=> Refactor end-to-end tests, Add firecracker-unikraft tests

README.md, docs/Urunc-Hypervisors.md
Add new document describing the installation process for each hypervisor currently supported hy `urunc`
=> Add installation instructions for hypervisors

CONTRIBUTING.md
Add a short document to describe how people can contribute to the urunc project.
=> Add a CONTRIBUTING document

docs/Installation.md, pkg/unikontainers/hypervisors/spt.go, pkg/unikontainers/hypervisors/vmm.go, tests/crictl/crictl_test.go, tests/ctr/ctr_test.go, tests/nerdctl/nerdctl_test.go
This commit adds the following: 
* Handling for Spt unikernels 
* Testing for Spt using  nerdctl and crictl
=> Feat: Add Spt-handling

pkg/network/network.go, pkg/network/network_dynamic.go, pkg/unikontainers/unikontainers.go
This PR changes the current networking functionality of `urunc`:
In some cases (for example specific Kubernetes pods) multiple unikernel containers must run inside the same network namespace. Previous to this commit, `urunc` created one TAP device for each unikernel, but only the first TAP device created could actually provide functional networking. 
In this commit, instead of creating multiple TAP devices in the same network namespace, `urunc`  checks if any tap device is available in the current netns. If it is, it assumes a running unikernel is already present in the current netns and returns an error, because network functionality for more than one unikernels  is not yet implemented. If no TAP devices are available in the current netns, it creates a new tap device and sets TC rules …
=> network: delete TC rules and TAP device upon killing the unikernel

Makefile, go.mod, go.sum, pkg/unikontainers/config.go, pkg/unikontainers/config_test.go, pkg/unikontainers/ipc_test.go, pkg/unikontainers/storage.go, pkg/unikontainers/storage_test.go, pkg/unikontainers/unikontainers.go, pkg/unikontainers/utils.go, pkg/unikontainers/utils_test.go
This PR adds unit tests for the unikontainers pkg
=> Unit test for pkg/unikontainers

go.mod, go.sum
Update go.mod and go.sum following the latest changes in urunc's dependencies.
=> Update Go dependencies of urunc

mkdocs.yml, netlify.toml
Add basic config files to automate the build of docs. Also add netlify to provide deploy previews and to deploy the documentation in urunc.netlify.app
=> ci(docs): Add boilerplate infrastructure for docs

README.md, cmd/urunc/create.go, pkg/unikontainers/config.go, pkg/unikontainers/config_test.go, pkg/unikontainers/unikontainers.go
This commit introduces compatibility between urunc and Docker, allowing users to run unikernels using Docker as the high-level runtime.
=> feat: Add support for Docker

docs/Sample-images.md, docs/design/index.md, docs/developer-guide/contribute.md, docs/developer-guide/development.md, docs/developer-guide/index.md, docs/hypervisor-support.md, docs/index.md, docs/quickstart.md, docs/tutorials/How-to-urunc-on-k8s.md, docs/unikernel-support.md
This PR fixes any broken links remaining in the docs.
=> fix(docs): Fix broken links in docs

pkg/network/network_static.go
In the case of Knative, urunc makes use of static networking configuration for the unikernel/user-container. All the requests to the user-container go though the queue-proxy container and static networking has worked well for that case, by simply making queue proxy to use the static IP of the unikernel, instead of the localhost.
However, there is also the case where the user-container might interract directly with the outside world (e.g. making a new HTTP request). In that scenarion, the static networking faces a limitation. The IP of the unikernel is only known inside the network namespace of the container. Therefore, as soon as the package leaves the network namespace and reaches the destination, any reply will never get delivered to the unikernel, since it is an unknown IP.
One …
=> fix(knative): Enable NAT and IP forwarding in static networking

docs/index.md
This PR fixes the broken links in the docs index.
=> fix(docs): Fix broken links in index

CODE_OF_CONDUCT.md, MAINTAINERS.md, docs/developer-guide/Code-of-Conduct.md, docs/developer-guide/contribute.md, docs/developer-guide/maintainers.md
Add the files with the current maintainers and the Code of Conduct.
=> Add maintainers and Code of Conduct files

.github/workflows/stale.yml
Facilitate stale issue/PR cleanup
=> ci: Add workflow to cleanup stale issues/PRs

.github/workflows/unit_test.yml
Update forgotten runner tag for unit-tests
=> ci: Update unit test runner tap

.github/workflows/lint.yml, .github/workflows/vm_test.yml
This PR replaces KCLI with Incus to facilitate VM provisioning for the end to end testing of `urunc`.
=> Update VM test action to use Incus

.github/workflows/build-latest.yml, .github/workflows/build-trigger.yml, .github/workflows/build.yml, .github/workflows/vm_test.yml, .gitignore, .golangci.yml, Makefile, deployment/urunc-deploy/Dockerfile, deployment/urunc-deploy/runtimeclasses/runtimeclass.yaml, deployment/urunc-deploy/scripts/install.sh, deployment/urunc-deploy/urunc-cleanup/base/kustomization.yaml, deployment/urunc-deploy/urunc-cleanup/base/urunc-cleanup.yaml, deployment/urunc-deploy/urunc-cleanup/overlays/k3s/kustomization.yaml, deployment/urunc-deploy/urunc-cleanup/overlays/k3s/mount_k3s_conf.yaml, deployment/urunc-deploy/urunc-deploy/base/kustomization.yaml, deployment/urunc-deploy/urunc-deploy/base/urunc-deploy.yaml, deployment/urunc-deploy/urunc-deploy/overlays/k3s/kustomization.yaml, deployment/urunc-deploy/urunc-deploy/overlays/k3s/mount_k3s_conf.yaml, deployment/urunc-deploy/urunc-rbac/kustomization.yaml, deployment/urunc-deploy/urunc-rbac/urunc-rbac.yaml, docs/tutorials/How-to-urunc-on-k8s.md
Add urunc-deploy to allow for easy installation in k8s clusters
=> Feat urunc deploy

docs/hooks/copyright.py, docs/overrides/partials/copyright.html
Removing (c) years as per LF Legal request.
=> docs: Update website footer

README.md, docs/developer-guide/contribute.md, docs/developer-guide/development.md, docs/developer-guide/security.md, docs/developer-guide/timestamps.md, docs/hypervisor-support.md, docs/index.md, docs/installation.md, docs/package/pre-built.md, docs/package/reuse.md, docs/package/rootfs.md, docs/quickstart.md, docs/tutorials/How-to-urunc-on-k8s.md, docs/tutorials/Non-root-monitor-execution.md, docs/tutorials/eks-tutorial.md, docs/tutorials/existing-container-linux.md, docs/tutorials/knative.md, docs/unikernel-support.md
- Update the documentation pointing to the new urunc's repository url.
- Add Slack channel and maintainer's mailing list.
- Update instructions in docs to make copy commands easier.
=> Update documentation and add Slack channel

README.md, docs/developer-guide/index.md, docs/index.md
Update community meetings link with the link from the LF's meeting platform.
=> chore(docs): Update community meetings link

.github/contributors.yaml, .github/linters/urunc-dict.txt, .github/workflows/ci.yml, .github/workflows/kind_test.yml, docs/tutorials/Running-urunc-with-kind.md
This PR adds:
- A GitHub workflow file to run urunc using kind
- A tutorial in docs/tutorials explaining how to run urunc with kind
=> ci: Add workflow for running urunc with kind

.github/workflows/add-git-trailers.yml, .github/workflows/build-latest.yml, .github/workflows/build-trigger.yml, .github/workflows/build.yml, .github/workflows/ci_on_push.yml, .github/workflows/codeql.yml, .github/workflows/dependency-review.yml, .github/workflows/kind_test.yml, .github/workflows/lint.yml, .github/workflows/pr-merge.yml, .github/workflows/pr-takeover.yml, .github/workflows/scorecard.yml, .github/workflows/stale.yml, .github/workflows/unit_test.yml, .github/workflows/validate-files-and-commits.yml, .github/workflows/vm_test.yml
We should address issues raised by scorecard at: https://github.com/urunc-dev/urunc/security/code-scanning?query=is%3Aopen+branch%3Amain+severity%3Acritical
This PR is a first step, trying to address the critical ones.
=> ci: Harden workflows

pkg/unikontainers/config.go, pkg/unikontainers/config_test.go
urunc currently loads unikernel configuration from spec annotations or a JSON file without performing any validation. This leads to failures much later in the container lifecycle, typically during monitor spawning, with error messages that are difficult to trace back to the root cause.
This change introduces a validation step that runs immediately after the configuration is loaded.
=> feat(config): invalid unikernel configuration fail early #Issue133
